### ISSUE TITLE
Cmd+number does not open expected window

### ISSUE THREAD

**Issue by jsardev** [kasecato/vscode-intellij-idea-keybindings#99] opened 2017-12-18 07:23 UTC
So let me give an example:

1. I'm in Source Control window
2. I click `CMD+1` to open explorer
3. The window hides (?)
4. I click `CMD+1` again to open explorer
5. The window shows but still in Source Control option

All of this works the same for all the window shortcuts (cmd+number), except Search shortcut (cmd+3) - this one works as expected (switches always to Search window).

Any ideas? Is my configuration messed up, or is it just a bug? :)

**Comment by xc1427** [comment] 2018-01-15 09:15
To repair this, the following keybinding works,
```
{
        "key": "cmd+1",
        "command": "workbench.action.toggleSidebarVisibility",
        "when": "explorerViewletVisible" },
```
@kasecato As I see, the original keybinding relies on `"when": "!editorFocus"`, which is not consistent.

**Comment by sarneeh** [comment] 2018-01-16 08:21
I've fixed it for myself for now just by attaching numbers (`1, 2, 3, 4, 5`) to corresponding views (explorer, search, scm, debug, extensions). This may not be mapping to IntelliJ shortcuts but fixes my problem for now. I guess the expected behaviour (specific sidebar view is always showing up on specific key, even if sidebar is hidden) cannot be added now because the macro keybindings feature is missing (https://github.com/Microsoft/vscode/issues/871).

**Comment by xc1427** [comment] 2018-01-16 16:18
You can try VSCode version 1.20.0 insider. As a related issue (https://github.com/Microsoft/vscode/issues/41377) is fixed in this version, I think the regression within the Cmd+Number key binding disappears.

**Comment by kasecato** [comment] 2024-01-28 07:53
Fixed by vscode-side

**Closed by kasecato** 2024-01-28 07:53 UTC
