### ISSUE TITLE
Navigate to explorer, changes

### ISSUE THREAD

**Issue by quantuminformation** [kasecato/vscode-intellij-idea-keybindings#119] opened 2018-07-25 09:45 UTC
It would be nice to have for mac:

cmd + 1    -> explorer
cmd + 9  -> vcs changes

just like webstorm

**Comment by kasecato** [comment] 2018-07-28 04:15
Hi, @QuantumInformation 
These key bindings are already available. Please check it 👀

**Comment by garbagemule** [comment] 2018-08-15 09:45
It looks like the keybindings are as they should be, but I'm experiencing a case of "sticky panels":

1. Click on the Explorer icon; the Explorer opens.
2. Click on the Explorer icon again to close the Explorer.
3. Hit Cmd+3; Search opens.
4. Hit Cmd+1; the drawer closes.
5. Hit Cmd+1 again; the drawer reopens with Search.

In step 4, I expect the drawer to remain open, and I expect Search to be replaced by Explorer. And if that doesn't work, I expect step 5 to bring up Explorer rather than Search. At this point, the only way I can bring up the Explorer seems to be with Cmd+Shift+E or with a mouse click.

In fact, it looks like Search (Cmd+3) is the only panel that will override an already open one. Other hotkeys just appear to be opening or closing the drawer, regardless of what is currently in it. I can't tell if this is a Code issue or an issue with the bindings (or just my setup, but my user settings appear devoid of anything that would interfere), though.

@kasecato can you reproduce this behavior I'm experiencing? Or is everything just working perfectly on your end?

Here's what I'm running:
- macOS 10.12.6 Sierra
- Visual Studio Code 1.26.0
- IntelliJ IDEA Keybindings 0.2.24 (Jun 17, 2018)

**Closed** 2024-01-28 13:36 UTC
Labels: bug, enhancement
